apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: tax-calculator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: tax-calculator-api:lastest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
            - name: DB_NAME
              value: taxcalculator
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: jwt-secret
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: tax-calculator
spec:
  selector:
    app: api
  ports:
    - port: 8080